// Package security — incident_store_test.go
//
// Tests for the JSONL IncidentStore layer added to support
// `helix incident` (spec §6.7).

package security

import (
	"bytes"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"testing"
	"time"
)

// sampleIncident returns a fully-populated test record. Tests should
// mutate copies of this rather than share the pointer.
func sampleIncident() IncidentRecord {
	return IncidentRecord{
		ID:          "inc-001",
		Severity:    SeveritySEV1,
		Title:       "Test incident",
		Description: "Generated by incident_store_test",
		Status:      IncidentOpen,
		CreatedAt:   time.Date(2026, 7, 5, 12, 0, 0, 0, time.UTC),
		AgentID:     "agent-test",
	}
}

func TestIncidentFileStore_RoundTrip(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "incidents.jsonl")

	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore: %v", err)
	}
	defer store.Close()

	// Write 3 incidents.
	for i, id := range []string{"inc-001", "inc-002", "inc-003"} {
		rec := sampleIncident()
		rec.ID = id
		rec.Title = "Incident " + id
		rec.Severity = []Severity{SeveritySEV0, SeveritySEV1, SeveritySEV2}[i]
		if err := store.Record(rec); err != nil {
			t.Fatalf("Record %s: %v", id, err)
		}
	}

	// Verify file mode is 0o600 (operator-only read/write).
	info, err := os.Stat(path)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if perm := info.Mode().Perm(); perm != 0o600 {
		t.Errorf("file mode = %o, want 0o600", perm)
	}

	// Replay.
	loaded, err := store.ReplayIncidents()
	if err != nil {
		t.Fatalf("ReplayIncidents: %v", err)
	}
	if len(loaded) != 3 {
		t.Fatalf("got %d records, want 3", len(loaded))
	}
	for i, want := range []string{"inc-001", "inc-002", "inc-003"} {
		if loaded[i].ID != want {
			t.Errorf("record %d: ID = %q, want %q", i, loaded[i].ID, want)
		}
	}
}

func TestIncidentFileStore_Path(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "incidents.jsonl")
	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore: %v", err)
	}
	defer store.Close()
	if store.Path() != path {
		t.Errorf("Path() = %q, want %q", store.Path(), path)
	}
}

func TestIncidentFileStore_CloseIdempotent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "incidents.jsonl")
	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore: %v", err)
	}
	if err := store.Close(); err != nil {
		t.Errorf("first Close: %v", err)
	}
	if err := store.Close(); err != nil {
		t.Errorf("second Close (idempotent): %v", err)
	}
}

func TestIncidentWriterStore_NoPath(t *testing.T) {
	var buf bytes.Buffer
	store := NewIncidentWriterStore(&buf)
	if p := store.Path(); p != "" {
		t.Errorf("Path() = %q, want empty", p)
	}
	if err := store.Record(sampleIncident()); err != nil {
		t.Errorf("Record: %v", err)
	}
	if buf.Len() == 0 {
		t.Error("buffer is empty — no JSONL written")
	}
	// Verify the line is valid JSON.
	var got IncidentRecord
	line := bytes.TrimSpace(buf.Bytes())
	if err := json.Unmarshal(line, &got); err != nil {
		t.Fatalf("unmarshal: %v\nline: %s", err, line)
	}
	if got.ID != "inc-001" {
		t.Errorf("ID = %q, want inc-001", got.ID)
	}
}

func TestIncidentStore_RejectsInvalidRecord(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "incidents.jsonl")
	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore: %v", err)
	}
	defer store.Close()

	cases := []struct {
		name string
		rec  IncidentRecord
	}{
		{"empty ID", IncidentRecord{Severity: SeveritySEV1, Status: IncidentOpen, CreatedAt: time.Now()}},
		{"invalid severity", IncidentRecord{ID: "x", Severity: "BAD", Status: IncidentOpen, CreatedAt: time.Now()}},
		{"empty status", IncidentRecord{ID: "x", Severity: SeveritySEV1, CreatedAt: time.Now()}},
		{"zero CreatedAt", IncidentRecord{ID: "x", Severity: SeveritySEV1, Status: IncidentOpen}},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if err := store.Record(tc.rec); err == nil {
				t.Error("Record accepted invalid record; want error")
			}
		})
	}
}

func TestIncidentStore_LoadAllSkipsMalformed(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "incidents.jsonl")
	// Pre-populate with one good record + one bad line + a header comment.
	rec := sampleIncident()
	recBytes, _ := json.Marshal(rec)
	contents := append(recBytes, '\n')
	contents = append(contents, []byte("# comment line, ignored\n")...)
	contents = append(contents, []byte("{this is not valid json\n")...)
	contents = append(contents, []byte("\n")...) // blank line
	if err := os.WriteFile(path, contents, 0o600); err != nil {
		t.Fatalf("WriteFile: %v", err)
	}

	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore: %v", err)
	}
	defer store.Close()

	loaded, err := store.LoadAll()
	if err != nil {
		t.Fatalf("LoadAll: %v", err)
	}
	if len(loaded) != 1 {
		t.Errorf("got %d records, want 1 (malformed lines skipped)", len(loaded))
	}
	if len(loaded) > 0 && loaded[0].ID != "inc-001" {
		t.Errorf("ID = %q, want inc-001", loaded[0].ID)
	}
}

func TestIncidentStore_LoadAllNonexistentFile(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "does-not-exist.jsonl")
	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore (should not error on missing file): %v", err)
	}
	defer store.Close()

	loaded, err := store.LoadAll()
	if err != nil {
		t.Errorf("LoadAll on empty store: %v", err)
	}
	if len(loaded) != 0 {
		t.Errorf("got %d records, want 0", len(loaded))
	}
}

func TestIncidentStore_AppendIsAtomicUnderConcurrency(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "incidents.jsonl")
	store, err := NewIncidentFileStore(path)
	if err != nil {
		t.Fatalf("NewIncidentFileStore: %v", err)
	}
	defer store.Close()

	const n = 50
	var wg sync.WaitGroup
	wg.Add(n)
	for i := 0; i < n; i++ {
		go func(i int) {
			defer wg.Done()
			rec := sampleIncident()
			rec.ID = "inc-conc-" + string(rune('a'+i%26)) + "-" + time.Now().Format("150405.000000000")
			if err := store.Record(rec); err != nil {
				t.Errorf("concurrent Record: %v", err)
			}
		}(i)
	}
	wg.Wait()

	loaded, err := store.ReplayIncidents()
	if err != nil {
		t.Fatalf("ReplayIncidents: %v", err)
	}
	if len(loaded) != n {
		t.Errorf("got %d records, want %d", len(loaded), n)
	}
}

func TestExpandIncidentPath(t *testing.T) {
	home, err := os.UserHomeDir()
	if err != nil {
		t.Skipf("no home dir: %v", err)
	}
	cases := []struct {
		in, want string
	}{
		{"/abs/path", "/abs/path"},
		{"~", home},
		{"~/foo/bar", filepath.Join(home, "foo/bar")},
		{"relative/path", "relative/path"},
	}
	for _, tc := range cases {
		got, err := expandIncidentPath(tc.in)
		if err != nil {
			t.Errorf("expandIncidentPath(%q): %v", tc.in, err)
			continue
		}
		if got != tc.want {
			t.Errorf("expandIncidentPath(%q) = %q, want %q", tc.in, got, tc.want)
		}
	}
}

func TestFormatTimestamp(t *testing.T) {
	if got := FormatTimestamp(time.Time{}); got != "-" {
		t.Errorf("zero time = %q, want %q", got, "-")
	}
	ts := time.Date(2026, 7, 5, 12, 34, 56, 0, time.UTC)
	if got := FormatTimestamp(ts); got != "2026-07-05T12:34:56Z" {
		t.Errorf("formatted = %q, want %q", got, "2026-07-05T12:34:56Z")
	}
}

func TestDefaultIncidentPath(t *testing.T) {
	if !strings.HasPrefix(DefaultIncidentPath, "~/") {
		t.Errorf("DefaultIncidentPath = %q, want ~/-prefix", DefaultIncidentPath)
	}
}
